---
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  branchAnalysis:
    if: github.event.pull_request.merged == true
    name: Branch Analysis on PR merge
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 20.12.2
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      - name: SonarCloud Scan
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.branch.name=master
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
